# web server
server:
  port: 9080
  servlet:
    context-path: /myapp

# spring
spring:
  application:
    name: hello-druid
  datasource:
    url: jdbc:h2:tcp://192.168.1.2:9092/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

# logging
logging:
  level:
    root: INFO
    org:
      springframework: INFO

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:/mappers/*.xml
